### ISSUE TITLE
Luo HUD

### ISSUE THREAD

**Issue by JuTeu** [Teuhon-Rakennusyhtio/Jumpnaut#11]

**Comment by uf0ja** [comment]
- [x] pelaajan pää (jos otta dmg/kuollu nii joku indikaattori) 
- [x] pidettäville tavaroille mittari (vaakataso)
- [x] kolme elämää > kypäriä
- [x] joku muoto tms minkä päällä kaikki jutut on
- [x] r4x4lle joku mittari

item ikonit:

- [x] vasara
- [x] patteri
- [x] sirkkeli
- [x] nailgun
- [ ] ruuvimeisseli
- [ ] pommi
- [ ] joku avaruutee liittyvä höskä
